- hosts: pwdev
  become: yes
  become_method: sudo
  remote_user: ansible
  tasks:
    - name: create directory root nduka
      file:
        name: /peter
        state: directory
        mode: 0775

    - name: copy fstab file to nduka directory
      copy:
        src: /etc/fstab
        dest: /home/ansible/nduka
